### ISSUE TITLE
Use CheckPassword hook instead

### ISSUE THREAD

**Issue by Cynosphere** [VaasKahnGrim/FrenchCheck-2.0#2]
why give them the satisfaction of spawning in

**Comment by VaasKahnGrim** [comment]
because I don't feel like bothering to lookup the varargs for tho hook lol

**Comment by Cynosphere** [comment]
https://wiki.facepunch.com/gmod/GM:CheckPassword

wow, that hard

**Comment by VaasKahnGrim** [comment]
gunna be honest with you, I'm REALLLY lazy atm towards side projects. RN I have a map commission thats past due, a gamemode v3 update thats currently sitting at 80% completion, recovering from dental surgery and lastly trying to work on a discord bot. I made this thing primarily as a joke in like 5 mins(probably rounding up by a good 2 and a half mins here)

I'll get around to making it use CheckPassword at SOME point maybe

**Comment by VaasKahnGrim** [comment]
@Cynosphere I had 5 mins to kill, ended up updating it to use CheckPassword while I was stuck on the toilet. Enjoy https://github.com/VaasKahnGrim/FrenchCheck-2.0/commit/2c4b57ddbd71bb08f7f4471550a3a829582d48d0
